/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113211-g6caf34dbe0-20240104"
#endif /* AVUTIL_FFVERSION_H */
